// Auto-generated by scripts/fetch-repo-stats.mjs at build time.
// Don't edit by hand — regenerate via `npm run build`.

export interface RepoStats {
  stars: number;
  lang: string | null;
  pushed_at: string;
}

export const repoStats: Record<string, RepoStats> = {
  "Builder106/EconOS": {
    "lang": "JavaScript",
    "pushed_at": "2026-05-12T17:02:59Z",
    "stars": 0
  },
  "Builder106/ocaml_limit": {
    "lang": "OCaml",
    "pushed_at": "2026-05-12T02:55:49Z",
    "stars": 1
  },
  "Builder106/qforge": {
    "lang": "C",
    "pushed_at": "2026-05-13T12:57:28Z",
    "stars": 0
  },
  "Builder106/MicroMatch": {
    "lang": "Svelte",
    "pushed_at": "2026-05-18T21:42:36Z",
    "stars": 0
  },
  "Builder106/STAIJA": {
    "lang": "TypeScript",
    "pushed_at": "2026-05-20T01:46:00Z",
    "stars": 0
  },
  "Builder106/StudySprint": {
    "lang": "TypeScript",
    "pushed_at": "2026-05-18T21:42:46Z",
    "stars": 0
  }
};
